services:
  postgres:
    image: postgres:16-alpine
    container_name: techzone-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: techzone_computer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./Database/init.sql:/docker-entrypoint-initdb.d/01-init.sql

  redis:
    image: redis:7-alpine
    container_name: techzone-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio:latest
    container_name: techzone-minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: techzone-backend
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/techzone_computer
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SERVER_PORT: 8080
      VNPAY_TMN_CODE: ${VNPAY_TMN_CODE:-2QXUI4B4}
      VNPAY_HASH_SECRET: ${VNPAY_HASH_SECRET:-RAOCTXGU2XFZ8TGUSWUXZNYAEBGQOZAW}
      VNPAY_URL: ${VNPAY_URL:-https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
      VNPAY_RETURN_URL: ${VNPAY_RETURN_URL:-http://localhost:5173/checkout}
    depends_on:
      - postgres
      - redis

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: techzone-frontend
    restart: unless-stopped
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  redis_data:
  minio_data:
